ctw : ctw.cpp bitio_file.cpp ctw_bcoder.cpp ctw_bcoder_incr.cpp float_ex.cpp bitio.h bitio_file.h ctw_bcoder.h ctw_bcoder_incr.h errormac.h float_ex.h gradient.h
	g++ -o ctw ctw.cpp bitio_file.cpp ctw_bcoder.cpp ctw_bcoder_incr.cpp float_ex.cpp gradient.cpp
